create table livros(
    ID_LIVRO NOT NULL PRIMARY KEY,
    NOME_LIVRO VARCHAR(255) UNIQUE NOT NULL,
    AUTOR VARCHAR(255) NOT NULL,
    ANO_PUB VARCHAR(255) NOT NULL,
    GENERO VARCHAR(255) NOT NULL
)